title: Maritsa Norton # your name (or website title) here
logo: "/images/bw_profile_photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a passionate advocate for informed decision-making.  
  I use data science and common sense to craft simple solutions to complex problems.
  <br><br>
  Here are some of the Python projects I've worked on as I learn the language.
  <br><br>
  <a href="https://www.linkedin.com/in/maritsa-norton/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-6M0F4CDCR2 # your Google Analytics tracking ID here
